# Use an official Python runtime as a parent image
FROM python:3.9

WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Copy the entire project files to the container
COPY . /app/

# Expose port 8000 (assuming Django runs on this port)
EXPOSE 8000

# Define the command to run the Django server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

